### ISSUE TITLE
Rendering fails on 2013 Mac Pro with Dual AMD FirePro D500

### ISSUE THREAD

**Issue by latenitefilms** [latenitefilms/BRAWToolbox#25]
### Discussed in https://github.com/latenitefilms/BRAWToolbox/discussions/14

<div type='discussions-op-text'>

<sup>Originally posted by **tangierc** January  1, 2023</sup>
Hello Chris. One of the things I was particularly hopeful for is just bringing in Braw video that I can use in a proxy/original workflow and allow FCP or Sync-N-Link to do my syncing using XML. A large part of this equation is being able to relink clips as needed, but BRAW Toolbox imports are don't allow me access to FCP's native reveal in browser, reveal, in finder, and relinking capabilities. 

My proxies were already made using Premiere Pro and migrating the project to FCP, I wanted to link those proxies to their original counterpart using BRAW Toolbox and in the end send to Resolve for color. Would these capabilities be possible in a future update? I know this is a beta. As it stands I am unable to use BRAW Toolbox imports both due to playback and scrubbing performance issues (on an Intel Mac) and no access to FCP's native clip management features.

Thank you for all of your hard work.
</div>

**Comment by latenitefilms** [comment]
This will HOPEFULLY be fixed in the next public beta @tangierc.

**Comment by latenitefilms** [comment]
@tangierc has a 2013 Mac Pro with Dual AMD FirePro D500 and reports:

> Plugin Not Responding. On a 2013 Mac Pro with Dual AMD FirePro 500 GPUs, the BRAW clip plays fine inside the workflow extension window, but once it's in the FCP library the clip displays solid green and blue frames along with bits of the video footage when scrubbing or attempting playback. Then the clip goes offline with a plugin not responding notice. This is using FCP 10.6.5.

Jamie Lejeune has a 2019 Mac Pro with 2x W5700X GPU and reports:

> Dang, the new beta is actually a lot worse than the last version on my machine. Attempts at playback result in flashing green in the viewer. And then pretty quickly, sometimes within seconds, sometimes a minute or two, it locks up my entire system — not just FCP, but the whole OS. I have to do a hard restart holding down the power button to regain control. And, on that reboot, if I’m not fast enough to force quit FCP, it locks up the system all over again. I can’t even get far enough to check the implementation of the HDR. 
> 
> The last beta that I was testing didn’t have any of these issues. The only hiccups was occasionally the viewer image would turn blue, but that was usually because I kept changing the parameters or toggling the effect.

**Comment by tangierc** [comment]
My FCCP prefs were trashed before this test as I am also working on a GUI responsiveness issue for large projects. The previous beta, though still having the flashing blue and green frames at times, did respond better than the current beta.

I forgot to mention that I am using macOS Monterey 12.6.2 and not Ventura.

**Comment by latenitefilms** [comment]
@tangierc - It would still be really handy to have a look at your logs and crash logs.

You can find the log files here:

`/Users/YOUR-USER-NAME/Library/Group Containers/A5HDJTY9X5.com.latenitefilms.BRAWToolbox/Library/Application Support/`

You can find any crash reports here (basically anything with a BRAW in the file name):

`/Users/YOUR-USER-NAME/Library/Logs/DiagnosticReports`

You can upload here:

https://latenitefilms.digitalpigeon.com

Are you also able to share a screenshot of the options in the **Render/Share GPU** dropdown in FCPX Preferences?

<img width="741" alt="image" src="https://user-images.githubusercontent.com/22286696/212496705-5c8c8791-09ce-4f33-acfb-46a6dffb7d7c.png">

In the meantime, I'll have another look and try some different things - it's just tricky because I only currently have access to single GPU machines.

**Comment by tangierc** [comment]
Sure thing. I’ll prepare those things for you now.I’ve been using EtreCheck Pro also to see if I can isolate any problematic files just in case, but my system is otherwise performing well overall.

Tangier

**Comment by latenitefilms** [comment]
I'm uploading a new build to TestFlight now. Let me know if there's any improvement.

**Comment by latenitefilms** [comment]
Interestingly, @tangierc's GPUs just appear as one in the Final Cut Pro interface:

![FCP Render Share image](https://user-images.githubusercontent.com/22286696/212500504-fa5528b4-b0b5-4d08-9116-24df5a6ca256.png)

**Comment by tangierc** [comment]
Chris I just sent you a screen recording. Could it be that it only shows as one because in the 2013 Mac Pro one GPU is used for GPU processing and the other for driving the monitors? I used to think that both GPUs were fully accessible to any app, but it seems that not the case by design? I read about this not too long ago.

Tangier

**Comment by latenitefilms** [comment]
@tangierc - I believe the GPUs in the Trashcan 2013 Mac Pro work a bit differently to older and newer Cheese-grater Mac Pro models, and Mac with eGPUs.

I just saw your screen recording. As soon as FCPX marks a plugin as "not responding", it won't work again until you restart Final Cut Pro.

Let me know if the latest beta - 1.0.0 (21) - Public Beta 8 - offers any improvement?

**Comment by tangierc** [comment]
This version has flickering blue frames using browser and timeline playback, but the plugin error did not happen this time.

Thanks,

Tangier

**Comment by latenitefilms** [comment]
Can you send a screenshot of Activity Monitor on the Memory panel and with the GPU History open during playback?

**Comment by tangierc** [comment]
Here you go. Both of these taken while the BRAW clip was playing. GPU ranged from 15% to 19% in slot 1.

**Comment by latenitefilms** [comment]
@tangierc - Thanks for the new screen recording! Very helpful! To be honest, I have absolutely no idea why this is happening. It's not an issue with the BRAW SDK, as it's obviously playing fine in the Workflow Extension, and it's rendering frames normally in FCPX most of the time. Something in FxPlug4 is failing. I'll reach out to Apple and see if they have any words of wisdom.

I'm also waiting to hear back from Jamie Lejeune who has a 2019 Mac Pro with 2 x W5700X GPU (16GB VRAM). 

It could just be a VRAM issue as the Dual AMD FirePro D500 only has 3GB VRAM, as **1.0.0 (21) - Public Beta 8** is doing a single frame on the one GPU.

**Comment by tangierc** [comment]
Understood. I’ve been configuring a Mac Studio online. I wasn’t quite ready, but maybe I’ll make the jump soon. This machine has been working great for almost every project (except a few large ones). The obvious choice would be just to use my M1 Pro MBP, but that’s not practical for me the way I have my workstation set up and how I use the MBP from place to place. 

Here’s a pdf of the full specs on that braw file. I don’t know if it’s useful at all, but sending anything I can to provide insight.  This is using the MediaInfo app.

**Comment by tangierc** [comment]
I made sure to test other braw clips that I have as well just in case there was a problem with the first clip file. They all have LTC embedded. I don’t think that’d cause an issue, but want to be sure I mention that again to be transparent about all variables. 

Tangier

**Comment by latenitefilms** [comment]
@tangierc - Each time you get a blue render frame does it write something like `ERROR - Failed to get processedImage.` in `~/Library/Group Containers/A5HDJTY9X5.com.latenitefilms.BRAWToolbox/Library/Application Support/FxPlug.log`?

**Comment by latenitefilms** [comment]
(FYI: I don't think your attachments come through when you reply via email)

**Comment by tangierc** [comment]
Ahhh, thanks for that.

Tangier

**Comment by tangierc** [comment]
Chris, I think it does. Initially I tried to count them and I could, but then the blue flashes happened too fast and I couldn’t count them. I went into the FxPlug log and sure enough it seems that they’re happening that fast when I look at the time stamps. I check the clock before I started paying attention and pressing play so your thought is spot on.

Tangier

**Comment by latenitefilms** [comment]
@tangierc - Interestingly, all the crash reports you sent all seem to crash in similar code, in the AMD Metal Driver.

```
Thread 531 Crashed::  Dispatch queue: com.apple.root.user-interactive-qos
0   AMDMTLBronzeDriver            	    0x7ffa3347f029 amdBronzeMtlTextureStdWriteTile256ByteChunkedDisp3(void*, void*, unsigned int, unsigned int) + 52
1   AMDMTLBronzeDriver            	    0x7ffa3347c963 BronzeGenerateMicroTileAddresses2D(BronzeCpuTexInterfaceRec const*, ATIMipmapBufferHeader const*, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, void (*)(unsigned long long, unsigned int, unsigned int, unsigned int, void*), void*) + 1245
2   AMDMTLBronzeDriver            	    0x7ffa3347d356 amdMtlBronzeTextureStdReplaceTiles(BronzeCpuTexInterfaceRec const*, ATIMipmapBufferHeader const*, ati_si_format_info const*, unsigned long, unsigned int, unsigned long, unsigned long, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int) + 268
3   AMDMTLBronzeDriver            	    0x7ffa3347ce4a amdMtlBronzeTextureStdAccessRegion(BronzeCpuTexInterfaceRec const*, void (*)(BronzeCpuTexInterfaceRec const*, ATIMipmapBufferHeader const*, ati_si_format_info const*, unsigned long, unsigned int, unsigned long, unsigned long, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int), void (*)(BronzeCpuTexInterfaceRec const*, ATIMipmapBufferHeader const*, ati_si_format_info const*, unsigned long, unsigned int, unsigned long, unsigned long, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int), ATIMipmapBufferHeader const*, ati_si_format_info const*, unsigned long, unsigned int, unsigned long, unsigned long, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int) + 573
4   AMDMTLBronzeDriver            	    0x7ffa3347d1df amdMtlBronzeTextureStdReplaceRegion(BronzeCpuTexInterfaceRec const*, ATIMipmapBufferHeader const*, ati_si_format_info const*, void*, unsigned int, unsigned long, unsigned long, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int) + 294
5   AMDMTLBronzeDriver            	    0x7ffa335004f1 -[BronzeMtlTexture replaceRegion:mipmapLevel:withBytes:bytesPerRow:] + 564
6   BRAW Toolbox Renderer         	       0x10e25cd7e 0x10e250000 + 52606
7   FxPlug                        	       0x10e601d6d __123-[FxRemotePluginCoordinator tileablePlugin:renderWithState:withImageInputs:withOutput:rendererRegistryID:atTime:withReply:]_block_invoke + 254
8   libdispatch.dylib             	    0x7ff816ce60cc _dispatch_call_block_and_release + 12
9   libdispatch.dylib             	    0x7ff816ce7317 _dispatch_client_callout + 8
10  libdispatch.dylib             	    0x7ff816cf6c0c _dispatch_root_queue_drain + 673
11  libdispatch.dylib             	    0x7ff816cf725c _dispatch_worker_thread2 + 160
12  libsystem_pthread.dylib       	    0x7ff816e9af8a _pthread_wqthread + 256
13  libsystem_pthread.dylib       	    0x7ff816e99f57 start_wqthread + 15
```

```
Thread 69 Crashed::  Dispatch queue: com.apple.root.user-interactive-qos
0   libsystem_kernel.dylib        	    0x7ff8018e700e __pthread_kill + 10
1   libsystem_pthread.dylib       	    0x7ff80191d1ff pthread_kill + 263
2   libsystem_c.dylib             	    0x7ff801868d24 abort + 123
3   libsystem_c.dylib             	    0x7ff8018680cb __assert_rtn + 314
4   AMDMTLBronzeDriver            	    0x7ffa1e071a8a amdMtlBronzeCmdBufUpdateRsrc(BronzeCmdBufInfoRec*, MTLIOAccelResource*, unsigned int, unsigned int) (.cold.1) + 35
5   AMDMTLBronzeDriver            	    0x7ffa1df573bd amdMtlBronzeCmdBufUpdateRsrc(BronzeCmdBufInfoRec*, MTLIOAccelResource*, unsigned int, unsigned int) + 173
6   AMDMTLBronzeDriver            	    0x7ffa1dfef496 amdMtlBronzeHandleLoadActions(BronzeDeviceMembersRec*, BronzeSurfSyncMgrRec*, BronzeCmdBufInfoRec*, AMDBitVectorRec*, MTLRenderPassDescriptor const*, BronzeLoadStoreInfo*, ATI_BOOL) + 2128
7   AMDMTLBronzeDriver            	    0x7ffa1df764da -[BronzeMtlRenderCmdEncoder initWithCommandBuffer:descriptor:] + 1454
8   AMDMTLBronzeDriver            	    0x7ffa1df59a81 -[BronzeMtlCmdBuffer renderCommandEncoderWithDescriptor:] + 52
9   BRAW Toolbox Renderer         	       0x107a445d3 0x107a38000 + 50643
10  FxPlug                        	       0x107de9d6d __123-[FxRemotePluginCoordinator tileablePlugin:renderWithState:withImageInputs:withOutput:rendererRegistryID:atTime:withReply:]_block_invoke + 254
11  libdispatch.dylib             	    0x7ff8017650cc _dispatch_call_block_and_release + 12
12  libdispatch.dylib             	    0x7ff801766317 _dispatch_client_callout + 8
13  libdispatch.dylib             	    0x7ff801775c0c _dispatch_root_queue_drain + 673
14  libdispatch.dylib             	    0x7ff80177625c _dispatch_worker_thread2 + 160
15  libsystem_pthread.dylib       	    0x7ff801919f8a _pthread_wqthread + 256
16  libsystem_pthread.dylib       	    0x7ff801918f57 start_wqthread + 15
```

```
Thread 1 Crashed::  Dispatch queue: com.apple.root.user-interactive-qos
0   libsystem_kernel.dylib        	    0x7ff8018e700e __pthread_kill + 10
1   libsystem_pthread.dylib       	    0x7ff80191d1ff pthread_kill + 263
2   libsystem_c.dylib             	    0x7ff801868d24 abort + 123
3   libsystem_c.dylib             	    0x7ff8018680cb __assert_rtn + 314
4   AMDMTLBronzeDriver            	    0x7ffa1e071a8a amdMtlBronzeCmdBufUpdateRsrc(BronzeCmdBufInfoRec*, MTLIOAccelResource*, unsigned int, unsigned int) (.cold.1) + 35
5   AMDMTLBronzeDriver            	    0x7ffa1df573bd amdMtlBronzeCmdBufUpdateRsrc(BronzeCmdBufInfoRec*, MTLIOAccelResource*, unsigned int, unsigned int) + 173
6   AMDMTLBronzeDriver            	    0x7ffa1dfef496 amdMtlBronzeHandleLoadActions(BronzeDeviceMembersRec*, BronzeSurfSyncMgrRec*, BronzeCmdBufInfoRec*, AMDBitVectorRec*, MTLRenderPassDescriptor const*, BronzeLoadStoreInfo*, ATI_BOOL) + 2128
7   AMDMTLBronzeDriver            	    0x7ffa1df764da -[BronzeMtlRenderCmdEncoder initWithCommandBuffer:descriptor:] + 1454
8   AMDMTLBronzeDriver            	    0x7ffa1df59a81 -[BronzeMtlCmdBuffer renderCommandEncoderWithDescriptor:] + 52
9   BRAW Toolbox Renderer         	       0x10dc775d3 0x10dc6b000 + 50643
10  FxPlug                        	       0x10e01cd6d __123-[FxRemotePluginCoordinator tileablePlugin:renderWithState:withImageInputs:withOutput:rendererRegistryID:atTime:withReply:]_block_invoke + 254
11  libdispatch.dylib             	    0x7ff8017650cc _dispatch_call_block_and_release + 12
12  libdispatch.dylib             	    0x7ff801766317 _dispatch_client_callout + 8
13  libdispatch.dylib             	    0x7ff801775c0c _dispatch_root_queue_drain + 673
14  libdispatch.dylib             	    0x7ff80177625c _dispatch_worker_thread2 + 160
15  libsystem_pthread.dylib       	    0x7ff801919f8a _pthread_wqthread + 256
16  libsystem_pthread.dylib       	    0x7ff801918f57 start_wqthread + 15
```

```
Thread 53 Crashed::  Dispatch queue: com.apple.root.user-interactive-qos
0   libsystem_kernel.dylib        	    0x7ff8018e700e __pthread_kill + 10
1   libsystem_pthread.dylib       	    0x7ff80191d1ff pthread_kill + 263
2   libsystem_c.dylib             	    0x7ff801868d24 abort + 123
3   libsystem_c.dylib             	    0x7ff8018680cb __assert_rtn + 314
4   AMDMTLBronzeDriver            	    0x7ffa1e071a8a amdMtlBronzeCmdBufUpdateRsrc(BronzeCmdBufInfoRec*, MTLIOAccelResource*, unsigned int, unsigned int) (.cold.1) + 35
5   AMDMTLBronzeDriver            	    0x7ffa1df573bd amdMtlBronzeCmdBufUpdateRsrc(BronzeCmdBufInfoRec*, MTLIOAccelResource*, unsigned int, unsigned int) + 173
6   AMDMTLBronzeDriver            	    0x7ffa1dfef496 amdMtlBronzeHandleLoadActions(BronzeDeviceMembersRec*, BronzeSurfSyncMgrRec*, BronzeCmdBufInfoRec*, AMDBitVectorRec*, MTLRenderPassDescriptor const*, BronzeLoadStoreInfo*, ATI_BOOL) + 2128
7   AMDMTLBronzeDriver            	    0x7ffa1df764da -[BronzeMtlRenderCmdEncoder initWithCommandBuffer:descriptor:] + 1454
8   AMDMTLBronzeDriver            	    0x7ffa1df59a81 -[BronzeMtlCmdBuffer renderCommandEncoderWithDescriptor:] + 52
9   BRAW Toolbox Renderer         	       0x108b105d3 0x108b04000 + 50643
10  FxPlug                        	       0x108eb5d6d __123-[FxRemotePluginCoordinator tileablePlugin:renderWithState:withImageInputs:withOutput:rendererRegistryID:atTime:withReply:]_block_invoke + 254
11  libdispatch.dylib             	    0x7ff8017650cc _dispatch_call_block_and_release + 12
12  libdispatch.dylib             	    0x7ff801766317 _dispatch_client_callout + 8
13  libdispatch.dylib             	    0x7ff801775c0c _dispatch_root_queue_drain + 673
14  libdispatch.dylib             	    0x7ff80177625c _dispatch_worker_thread2 + 160
15  libsystem_pthread.dylib       	    0x7ff801919f8a _pthread_wqthread + 256
16  libsystem_pthread.dylib       	    0x7ff801918f57 start_wqthread + 15
```

```
Thread 53 Crashed::  Dispatch queue: com.apple.root.user-interactive-qos
0   libsystem_kernel.dylib        	    0x7ff8018e700e __pthread_kill + 10
1   libsystem_pthread.dylib       	    0x7ff80191d1ff pthread_kill + 263
2   libsystem_c.dylib             	    0x7ff801868d24 abort + 123
3   libsystem_c.dylib             	    0x7ff8018680cb __assert_rtn + 314
4   AMDMTLBronzeDriver            	    0x7ffa1e071a8a amdMtlBronzeCmdBufUpdateRsrc(BronzeCmdBufInfoRec*, MTLIOAccelResource*, unsigned int, unsigned int) (.cold.1) + 35
5   AMDMTLBronzeDriver            	    0x7ffa1df573bd amdMtlBronzeCmdBufUpdateRsrc(BronzeCmdBufInfoRec*, MTLIOAccelResource*, unsigned int, unsigned int) + 173
6   AMDMTLBronzeDriver            	    0x7ffa1dfef496 amdMtlBronzeHandleLoadActions(BronzeDeviceMembersRec*, BronzeSurfSyncMgrRec*, BronzeCmdBufInfoRec*, AMDBitVectorRec*, MTLRenderPassDescriptor const*, BronzeLoadStoreInfo*, ATI_BOOL) + 2128
7   AMDMTLBronzeDriver            	    0x7ffa1df764da -[BronzeMtlRenderCmdEncoder initWithCommandBuffer:descriptor:] + 1454
8   AMDMTLBronzeDriver            	    0x7ffa1df59a81 -[BronzeMtlCmdBuffer renderCommandEncoderWithDescriptor:] + 52
9   BRAW Toolbox Renderer         	       0x10f6b45d3 0x10f6a8000 + 50643
10  FxPlug                        	       0x1108cbd6d __123-[FxRemotePluginCoordinator tileablePlugin:renderWithState:withImageInputs:withOutput:rendererRegistryID:atTime:withReply:]_block_invoke + 254
11  libdispatch.dylib             	    0x7ff8017650cc _dispatch_call_block_and_release + 12
12  libdispatch.dylib             	    0x7ff801766317 _dispatch_client_callout + 8
13  libdispatch.dylib             	    0x7ff801775c0c _dispatch_root_queue_drain + 673
14  libdispatch.dylib             	    0x7ff80177625c _dispatch_worker_thread2 + 160
15  libsystem_pthread.dylib       	    0x7ff801919f8a _pthread_wqthread + 256
16  libsystem_pthread.dylib       	    0x7ff801918f57 start_wqthread + 15
```

```
Thread 98 Crashed::  Dispatch queue: com.apple.root.user-interactive-qos
0   libsystem_kernel.dylib        	    0x7ff81125b00e __pthread_kill + 10
1   libsystem_pthread.dylib       	    0x7ff8112911ff pthread_kill + 263
2   libsystem_c.dylib             	    0x7ff8111dcd24 abort + 123
3   libsystem_c.dylib             	    0x7ff8111dc0cb __assert_rtn + 314
4   AMDMTLBronzeDriver            	    0x7ffa2d9e5a8a amdMtlBronzeCmdBufUpdateRsrc(BronzeCmdBufInfoRec*, MTLIOAccelResource*, unsigned int, unsigned int) (.cold.1) + 35
5   AMDMTLBronzeDriver            	    0x7ffa2d8cb3bd amdMtlBronzeCmdBufUpdateRsrc(BronzeCmdBufInfoRec*, MTLIOAccelResource*, unsigned int, unsigned int) + 173
6   AMDMTLBronzeDriver            	    0x7ffa2d963496 amdMtlBronzeHandleLoadActions(BronzeDeviceMembersRec*, BronzeSurfSyncMgrRec*, BronzeCmdBufInfoRec*, AMDBitVectorRec*, MTLRenderPassDescriptor const*, BronzeLoadStoreInfo*, ATI_BOOL) + 2128
7   AMDMTLBronzeDriver            	    0x7ffa2d8ea4da -[BronzeMtlRenderCmdEncoder initWithCommandBuffer:descriptor:] + 1454
8   AMDMTLBronzeDriver            	    0x7ffa2d8cda81 -[BronzeMtlCmdBuffer renderCommandEncoderWithDescriptor:] + 52
9   BRAW Toolbox Renderer         	       0x10340a5d3 0x1033fe000 + 50643
10  FxPlug                        	       0x1037afd6d __123-[FxRemotePluginCoordinator tileablePlugin:renderWithState:withImageInputs:withOutput:rendererRegistryID:atTime:withReply:]_block_invoke + 254
11  libdispatch.dylib             	    0x7ff8110d90cc _dispatch_call_block_and_release + 12
12  libdispatch.dylib             	    0x7ff8110da317 _dispatch_client_callout + 8
13  libdispatch.dylib             	    0x7ff8110e9c0c _dispatch_root_queue_drain + 673
14  libdispatch.dylib             	    0x7ff8110ea25c _dispatch_worker_thread2 + 160
15  libsystem_pthread.dylib       	    0x7ff81128df8a _pthread_wqthread + 256
16  libsystem_pthread.dylib       	    0x7ff81128cf57 start_wqthread + 15
```

```
Thread 2 Crashed::  Dispatch queue: com.apple.root.user-interactive-qos
0   libsystem_kernel.dylib        	    0x7ff81125b00e __pthread_kill + 10
1   libsystem_pthread.dylib       	    0x7ff8112911ff pthread_kill + 263
2   libsystem_c.dylib             	    0x7ff8111dcd24 abort + 123
3   libsystem_c.dylib             	    0x7ff8111dc0cb __assert_rtn + 314
4   AMDMTLBronzeDriver            	    0x7ffa2d9e5a8a amdMtlBronzeCmdBufUpdateRsrc(BronzeCmdBufInfoRec*, MTLIOAccelResource*, unsigned int, unsigned int) (.cold.1) + 35
5   AMDMTLBronzeDriver            	    0x7ffa2d8cb3bd amdMtlBronzeCmdBufUpdateRsrc(BronzeCmdBufInfoRec*, MTLIOAccelResource*, unsigned int, unsigned int) + 173
6   AMDMTLBronzeDriver            	    0x7ffa2d963496 amdMtlBronzeHandleLoadActions(BronzeDeviceMembersRec*, BronzeSurfSyncMgrRec*, BronzeCmdBufInfoRec*, AMDBitVectorRec*, MTLRenderPassDescriptor const*, BronzeLoadStoreInfo*, ATI_BOOL) + 2128
7   AMDMTLBronzeDriver            	    0x7ffa2d8ea4da -[BronzeMtlRenderCmdEncoder initWithCommandBuffer:descriptor:] + 1454
8   AMDMTLBronzeDriver            	    0x7ffa2d8cda81 -[BronzeMtlCmdBuffer renderCommandEncoderWithDescriptor:] + 52
9   BRAW Toolbox Renderer         	       0x1011ff5d3 0x1011f3000 + 50643
10  FxPlug                        	       0x1015a4d6d __123-[FxRemotePluginCoordinator tileablePlugin:renderWithState:withImageInputs:withOutput:rendererRegistryID:atTime:withReply:]_block_invoke + 254
11  libdispatch.dylib             	    0x7ff8110d90cc _dispatch_call_block_and_release + 12
12  libdispatch.dylib             	    0x7ff8110da317 _dispatch_client_callout + 8
13  libdispatch.dylib             	    0x7ff8110e9c0c _dispatch_root_queue_drain + 673
14  libdispatch.dylib             	    0x7ff8110ea25c _dispatch_worker_thread2 + 160
15  libsystem_pthread.dylib       	    0x7ff81128df8a _pthread_wqthread + 256
16  libsystem_pthread.dylib       	    0x7ff81128cf57 start_wqthread + 15
```

```
Thread 1 Crashed::  Dispatch queue: com.apple.root.user-interactive-qos
0   libsystem_kernel.dylib        	    0x7ff81125b00e __pthread_kill + 10
1   libsystem_pthread.dylib       	    0x7ff8112911ff pthread_kill + 263
2   libsystem_c.dylib             	    0x7ff8111dcd24 abort + 123
3   libsystem_c.dylib             	    0x7ff8111dc0cb __assert_rtn + 314
4   AMDMTLBronzeDriver            	    0x7ffa2d9e5a8a amdMtlBronzeCmdBufUpdateRsrc(BronzeCmdBufInfoRec*, MTLIOAccelResource*, unsigned int, unsigned int) (.cold.1) + 35
5   AMDMTLBronzeDriver            	    0x7ffa2d8cb3bd amdMtlBronzeCmdBufUpdateRsrc(BronzeCmdBufInfoRec*, MTLIOAccelResource*, unsigned int, unsigned int) + 173
6   AMDMTLBronzeDriver            	    0x7ffa2d963496 amdMtlBronzeHandleLoadActions(BronzeDeviceMembersRec*, BronzeSurfSyncMgrRec*, BronzeCmdBufInfoRec*, AMDBitVectorRec*, MTLRenderPassDescriptor const*, BronzeLoadStoreInfo*, ATI_BOOL) + 2128
7   AMDMTLBronzeDriver            	    0x7ffa2d8ea4da -[BronzeMtlRenderCmdEncoder initWithCommandBuffer:descriptor:] + 1454
8   AMDMTLBronzeDriver            	    0x7ffa2d8cda81 -[BronzeMtlCmdBuffer renderCommandEncoderWithDescriptor:] + 52
9   BRAW Toolbox Renderer         	       0x10a9d75d3 0x10a9cb000 + 50643
10  FxPlug                        	       0x10ad7cd6d __123-[FxRemotePluginCoordinator tileablePlugin:renderWithState:withImageInputs:withOutput:rendererRegistryID:atTime:withReply:]_block_invoke + 254
11  libdispatch.dylib             	    0x7ff8110d90cc _dispatch_call_block_and_release + 12
12  libdispatch.dylib             	    0x7ff8110da317 _dispatch_client_callout + 8
13  libdispatch.dylib             	    0x7ff8110e9c0c _dispatch_root_queue_drain + 673
14  libdispatch.dylib             	    0x7ff8110ea25c _dispatch_worker_thread2 + 160
15  libsystem_pthread.dylib       	    0x7ff81128df8a _pthread_wqthread + 256
16  libsystem_pthread.dylib       	    0x7ff81128cf57 start_wqthread + 15
```

```
Thread 168 Crashed::  Dispatch queue: com.apple.root.user-interactive-qos
0   libsystem_kernel.dylib        	    0x7ff81125b00e __pthread_kill + 10
1   libsystem_pthread.dylib       	    0x7ff8112911ff pthread_kill + 263
2   libsystem_c.dylib             	    0x7ff8111dcd24 abort + 123
3   libsystem_c.dylib             	    0x7ff8111dc0cb __assert_rtn + 314
4   AMDMTLBronzeDriver            	    0x7ffa2d9e5a8a amdMtlBronzeCmdBufUpdateRsrc(BronzeCmdBufInfoRec*, MTLIOAccelResource*, unsigned int, unsigned int) (.cold.1) + 35
5   AMDMTLBronzeDriver            	    0x7ffa2d8cb3bd amdMtlBronzeCmdBufUpdateRsrc(BronzeCmdBufInfoRec*, MTLIOAccelResource*, unsigned int, unsigned int) + 173
6   AMDMTLBronzeDriver            	    0x7ffa2d963496 amdMtlBronzeHandleLoadActions(BronzeDeviceMembersRec*, BronzeSurfSyncMgrRec*, BronzeCmdBufInfoRec*, AMDBitVectorRec*, MTLRenderPassDescriptor const*, BronzeLoadStoreInfo*, ATI_BOOL) + 2128
7   AMDMTLBronzeDriver            	    0x7ffa2d8ea4da -[BronzeMtlRenderCmdEncoder initWithCommandBuffer:descriptor:] + 1454
8   AMDMTLBronzeDriver            	    0x7ffa2d8cda81 -[BronzeMtlCmdBuffer renderCommandEncoderWithDescriptor:] + 52
9   BRAW Toolbox Renderer         	       0x10abec5d3 0x10abe0000 + 50643
10  FxPlug                        	       0x10af91d6d __123-[FxRemotePluginCoordinator tileablePlugin:renderWithState:withImageInputs:withOutput:rendererRegistryID:atTime:withReply:]_block_invoke + 254
11  libdispatch.dylib             	    0x7ff8110d90cc _dispatch_call_block_and_release + 12
12  libdispatch.dylib             	    0x7ff8110da317 _dispatch_client_callout + 8
13  libdispatch.dylib             	    0x7ff8110e9c0c _dispatch_root_queue_drain + 673
14  libdispatch.dylib             	    0x7ff8110ea25c _dispatch_worker_thread2 + 160
15  libsystem_pthread.dylib       	    0x7ff81128df8a _pthread_wqthread + 256
16  libsystem_pthread.dylib       	    0x7ff81128cf57 start_wqthread + 15
```

```
Thread 98 Crashed::  Dispatch queue: com.apple.root.user-interactive-qos
0   libsystem_kernel.dylib        	    0x7ff81125b00e __pthread_kill + 10
1   libsystem_pthread.dylib       	    0x7ff8112911ff pthread_kill + 263
2   libsystem_c.dylib             	    0x7ff8111dcd24 abort + 123
3   libsystem_c.dylib             	    0x7ff8111dc0cb __assert_rtn + 314
4   AMDMTLBronzeDriver            	    0x7ffa2d9e5a8a amdMtlBronzeCmdBufUpdateRsrc(BronzeCmdBufInfoRec*, MTLIOAccelResource*, unsigned int, unsigned int) (.cold.1) + 35
5   AMDMTLBronzeDriver            	    0x7ffa2d8cb3bd amdMtlBronzeCmdBufUpdateRsrc(BronzeCmdBufInfoRec*, MTLIOAccelResource*, unsigned int, unsigned int) + 173
6   AMDMTLBronzeDriver            	    0x7ffa2d963496 amdMtlBronzeHandleLoadActions(BronzeDeviceMembersRec*, BronzeSurfSyncMgrRec*, BronzeCmdBufInfoRec*, AMDBitVectorRec*, MTLRenderPassDescriptor const*, BronzeLoadStoreInfo*, ATI_BOOL) + 2128
7   AMDMTLBronzeDriver            	    0x7ffa2d8ea4da -[BronzeMtlRenderCmdEncoder initWithCommandBuffer:descriptor:] + 1454
8   AMDMTLBronzeDriver            	    0x7ffa2d8cda81 -[BronzeMtlCmdBuffer renderCommandEncoderWithDescriptor:] + 52
9   BRAW Toolbox Renderer         	       0x10a8ce5d3 0x10a8c2000 + 50643
10  FxPlug                        	       0x10ac73d6d __123-[FxRemotePluginCoordinator tileablePlugin:renderWithState:withImageInputs:withOutput:rendererRegistryID:atTime:withReply:]_block_invoke + 254
11  libdispatch.dylib             	    0x7ff8110d90cc _dispatch_call_block_and_release + 12
12  libdispatch.dylib             	    0x7ff8110da317 _dispatch_client_callout + 8
13  libdispatch.dylib             	    0x7ff8110e9c0c _dispatch_root_queue_drain + 673
14  libdispatch.dylib             	    0x7ff8110ea25c _dispatch_worker_thread2 + 160
15  libsystem_pthread.dylib       	    0x7ff81128df8a _pthread_wqthread + 256
16  libsystem_pthread.dylib       	    0x7ff81128cf57 start_wqthread + 15
```

**Comment by latenitefilms** [comment]
@tangierc - I'm uploading a new build shortly with some very minor changes. I'm not sure it'll have any impact, but I guess we'll wait and see.

**Comment by tangierc** [comment]
Sound good. I’ll give a go.

Tangier

**Comment by latenitefilms** [comment]
**1.0.0 (22) - Public Beta 9** should now be up.

**Comment by tangierc** [comment]
Great. I restarted FCP after updating BRAW Toolbox. When I played back the existing BRAW clips in the last test library, the first one played beginning to end without any blue or green flashing frames, but did stutter occasionally like toggling rapidly between previous and next frames before it continued to play. The second clip when selected showed a blue frame in the viewer, then played with no flashing color, but stuttered more.

Next I created a new library bringing in those clips. As usual they play fine in the plugin window, but once in the library I got a solid blue frames for one of them - the filmstrip view and in the viewer. Playback had flashing frames again and stutter playback from time to time.

This has got to be a really strange issue to nail down. Selecting a clip at first always seems to cause something odd to happen before I play it back.

**Comment by latenitefilms** [comment]
Are you able to send me the log files again?

Can you also click the **Help** menu item in Final Cut Pro, then hold down **OPTION** and click **Gather App Diagnostics**? After a few minutes it'll create a ZIP file on your Desktop with all Final Cut Pro's logs. I'll try sending them to Apple as well to see if they have any ideas.

**Comment by tangierc** [comment]
Sending now.

**Comment by latenitefilms** [comment]
@tangierc - Interestingly, all the errors in your most recent logs are sandboxing issues, not graphics issues.

Can you try closing all the existing test libraries, restart your computer, then create a completely new library?

**Comment by tangierc** [comment]
Uploading files for test 8 in just a moment.

**Comment by latenitefilms** [comment]
@tangierc - I've just uploaded **1.0.0 (23) - Public Beta 10**. The only change that MIGHT help is that I've updated the FxPlug4 API to the latest version after chatting with Apple.

I still haven't heard back from Jamie Lejeune (who has a 2019 Mac Pro with 2 x W5700X GPU) as to whether or not he's still having blue frames. If he does, then we know it's some kind of dual GPU bug. If he doesn't, then my best guess is that your 10-year-old machine is simply running out of VRAM - although that doesn't really explain why the same BRAW files work fine in DaVinci Resolve. It could be that Resolve is using OpenCL instead of Metal for those older GPUs?

**Comment by tangierc** [comment]
I hadn’t considered that.  Just curious, based on the work you’re doing with BRAW Toolbox, the BRAW SDK, and what Apple’s APIs will allow, is it even possible to reconnect a ProRes Proxy of a BRAW to its original .braw file like I do with my RED files? I would love even just to have that knowing I can’t play those clips back, but I could (technically in FCP) switch over to originals, then send it over to Resolve via XML for color.  Ideally, you’re right that one should be able to use the BRAW files at a fraction of the decoding processing even on older machines as evidenced in Resolve, but if that doesn’t workout with BRAW Toolbox enough to edit with, then the options are use Resolve completely (with or without other project formats other than .braw) of use FCP with proxies of the .braw and conform in Resolve later; perhaps manually. I have yet to find out if Resolve can batch replace clips given a directory same named clips (swapping out the proxy for the .braw). It definitely works one at a time.

The Finder doesn’t even acknowledge .braw files as “movie” files when doing a search by Kind.

Thanks

**Comment by latenitefilms** [comment]
Jamie Lejeune reports that the latest beta works well on his 2019 Mac Pro with Dual W5700X GPU.

If the latest beta still isn't working for you, I can only assume it's because the 2013 Mac Pro with Dual AMD FirePro D500 either doesn't have enough VRAM, or based on the crashes you had above, there's a bug in the AMD Metal Drivers that it's unlikely that Apple will ever fix, given that the Mac Pro (2019) is now the only supported Mac Pro on macOS Ventura.

FWIW - BRAW Toolbox works just as well on my Intel 16-inch MacBook Pro, as it does on my 16-inch M1 Max MacBook Pro - I get similar performance to Resolve, even at Full Debayer.

I'm also waiting to hear back from someone who has a 2013 Mac Pro with Dual D700 - so will be very interesting to hear if they also have issues or not.

It's also entirely possible that you might just have faulty hardware - the 2013 Mac Pro's are pretty notorious for overheating and burning out GPUs. Whilst BRAW Toolbox uses the same BRAW SDK for de-bayering the BRAW files, it still uses FxPlug4 for the Final Cut Pro rendering, and Final Cut Pro tries to use all the GPUs and CPUs it can get it hands on - so it might just be pushing your system to the max.

You could also try [contacting Apple Support](https://support.apple.com/en-au/final-cut-pro) directly, as they might be able to rule out any hardware issues?

> is it even possible to reconnect a ProRes Proxy of a BRAW to its original .braw file like I do with my RED files?

No, you'll never be able to add proxies or relink the Synchronised Clips or Multicam Clips that come out of BRAW Toolbox. BRAW Toolbox clips don't contain any video files - they simply contain a Black Generator with a BRAW Toolbox effect applied to them.

However, once I finish #23, you will be able to  "Convert BRAW clips to MOV's within an EVENT".

In the meantime however, if you did have issues with BRAW in FCPX, you can today send your FCPX project to Resolve using the Toolbox in the Workflow Extension - by all reports, it works well.

> I have yet to find out if Resolve can batch replace clips given a directory same named clips (swapping out the proxy for the .braw). It definitely works one at a time.

Yes, Resolve has very powerful and flexible conforming tools - so you can easily relink to different assets, in a variety of different ways.

> The Finder doesn’t even acknowledge .braw files as “movie” files when doing a search by Kind.

Try this instead:

<img width="274" alt="image" src="https://user-images.githubusercontent.com/22286696/212564349-17991cb9-f928-4225-a186-697ff09d8330.png">

**Comment by tangierc** [comment]
Thanks for all of this testing with me Chris. I am sure an upgrade is long overdue, though this machine has been working great for me for many projects except for the lack of QuickSync.

Tangier

**Comment by latenitefilms** [comment]
Just to confirm... are you still having the same issues with the latest beta?

**Comment by tangierc** [comment]
Yes, I am still having those issues. The only thing newly introduced with the last two betas I believe are the stuttering effect when playing back the footage.

Tangier

**Comment by latenitefilms** [comment]
Are you able to record me a screen recording of things not working in Final Cut Pro, then quit Final Cut Pro and open Resolve and show the same clips with the same settings working? I'll try send to Apple and Blackmagic. If you can keep the Activity Monitor's CPU and GPU history's on top too, that would be handy. Maybe also show playing BRAW with the Blackmagic BRAW Player?

Maybe also try run Apple Diagnostics on your machine just to rule out any hardware issues?

https://support.apple.com/en-au/HT202731

**Comment by tangierc** [comment]
Chris, I am uploading these elements now.

Tangier

**Comment by tangierc** [comment]
I was using Resolve 18.1.2 in the screen recording by the way.

Tangier

**Comment by latenitefilms** [comment]
Legend, thank you!

**Comment by tangierc** [comment]
Lol…I had to google Aussie terms.  I was thinking you meant to reply to someone else whose name happened to be “Legend”.  

Thanks

**Comment by latenitefilms** [comment]
@tangierc - Does everything also play back perfectly in the "Blackmagic RAW Player"?

<img width="270" alt="image" src="https://user-images.githubusercontent.com/22286696/212575460-d6d0a854-e5bf-42e1-a80a-c9dfa11e1efe.png">

**Comment by tangierc** [comment]
It plays and scrubs fine in Blackmagic RAW Player.

Tangier

**Comment by latenitefilms** [comment]
Sadly, I'm out of ideas. Hopefully some more Mac Pro users come forward with feedback, so we can determine if it's your machine specifically, or a more general issue. I've emailed everything to Apple, so we'll see if they have any ideas, but it's unlikely. I'll try hunt down a Mac Pro Trashcan locally as well.

**Comment by latenitefilms** [comment]
@tangierc - Oh, sorry, one more random idea... have you tried disconnecting everything but a single monitor, and no AV Output? Does that make any difference? If not, can you try using a single monitor on another port? Ideally disconnect everything except a single monitor, keyboard and mouse. Make sure no other software is running.

**Comment by tangierc** [comment]
Hey Chris. I did a quick test this morning with version 1.0.0 (25) I used a BRAW clip on the Mac Pro’s internal SSD and one monitor. All other drives and peripherals were disconnected. After the clip was in the FCP library, It showed green when I selected a frame, but then scrubbing and playback seemed OK.  IT still had that stutter or jitter from time to time that I mentioned. It never flashed any blue or green color after the first initial selection. I’d like to try it again when I get home on other BRAW clips.  I was running out the house for work and getting kids to school when I did this, but it still was a full test with a fresh library after a restart. No apps running other than Adobe Creative Cloud in the menu bar from the launch daemon.

As I write this from my old laptop (2016 15” Intel MBP) I just noticed that BRAW Toolbox is at (26). I just tested two clips downloaded from Blackmagic and using BRAW Toolbox 1.0.0 (26). They worked great on my 2016 Intel MBP. I need to test those clips I’ve been testing on this computer later after work. I don’t have them handy. This way I can really see the difference (if there is any) on two Intel Macs. We already know it works on the M1 MBP.

So the questions are:
- Is the media I have the problem?
- Is there something about the Mac Pro’s GPU setup that it would perform worse than my 2016 MBP 2.7 GHz Quad-Core Intel Core i7. 

I’ll find out when I get home.


Tangier

**Comment by latenitefilms** [comment]
My GUESS is either you're running out of VRAM, or one of your GPUs is actually faulty, but you need to really push it before it fails.

There's now 182 people who have signed up for TestFlight, and I haven't had any other reports of this stuttering behaviour. I've tried posting to a Mac Pro specific Facebook Group too, but I haven't had any negative feedback yet.

**Comment by tangierc** [comment]
Hey Chris. Just tested those existing clips I’ve been testing on my other Intel machine - the 2016 MBP.  Performance is great. Smooth playback and scrubbing. Is much much better than my Mac Pro. Why that is, I don’t know.  The MBP has Intel HD Graphics 530 with 1536 MB. I don’t get the green or blue flashes. I only noticed the stutter once.

My original 2013 Mac Pro died early last year and wouldn’t power on. Apple essentially rebuilt it in April of last years for a pretty low cost (a little above $450 with labor) compared to the actual cost of part. It made total sense to repair. So essentially everything should (hopefully) not be faulty.
![Screen Shot 2023-01-17 at 6 17 14 PM](https://user-images.githubusercontent.com/9577806/213065752-cc0553c8-491b-4b4f-861d-733fe5ba4e6c.png)

**Comment by latenitefilms** [comment]
I've tested BRAW Toolbox on some very crappy Mac's and it still works great. My GUESS is that your Mac Pro is faulty, however, I have absolutely no idea why those faults aren't showing when using DaVinci Resolve. I can only assume it's just because of the different ways we're processing things.

Things you can try:

- Run hardware diagnostics as discussed earlier
- Create another user on your Mac and see if that makes any difference
- Install a fresh macOS install on an external drive or another partition and see if that makes any difference

Given you have other performance issues with your Mac Pro that are hard to put your finger on, it's entirely possible that a lot of your weird softwares issues are simply due to failing hardware.

It would be a lot easier to diagnose if someone with the same system was able to test - but I haven't been able to get any specific feedback from other 2013 Mac Pro users yet.

I do note that one of the moderators in the Mac Pro Facebook group I posted to says:

> D500 and D700 GPU’s are notorious for failing. D300’s are not affected so try on a Pro with those

I'll keep this issue open for now until we get feedback from other Mac Pro users, however, if someone comes back with Dual D500's and no issues, then we'll just have to assume this issue is specific to your machine.

**Comment by tangierc** [comment]
Thanks for the advice. I’ll definitely run a hardware test.

**Comment by tangierc** [comment]
Hardware test found no issues.  So with regard to my Intel machines we’re at:

It works just fine on a 2013 Mac Pro with two AMD FirePro D500s as evidenced in Da Vinci Resolve 18
It don’ts work well on the same computer in FCP 10.6.5
It works just fine (significantly better than the Mac Pro above) on a 2016 Intel i7 MacBook Pro using FCP 10.6.5

Somewhere in there must be an issue with the GPU and FCP on the Mac Pro.

**Comment by latenitefilms** [comment]
If you look at Activity Monitor, is Resolve and FCPX both accessing the same GPU during BRAW Playback? It could be a matter of Resolve splitting across the BRAW processing across both GPUs, whereas BRAW Toolbox is only using one GPU for decoding - which could explain hitting a VRAM limit?

**Comment by tangierc** [comment]
I’ll check, but wouldn’t that be odd then that the Intel MBP works great and yet just one of the the AMD D500s have more VRAM than the MBPs 1536 MB?

**Comment by tangierc** [comment]
Here are the difference; same clips in Resolve and FCP - both from the media pool and browser respectively, not the timeline.
![Screen Shot 2023-01-17 at 8 06 42 PM](https://user-images.githubusercontent.com/9577806/213081604-bcc33fc2-f3c0-4940-9a05-94876d3a53fa.png)
![Screen Shot 2023-01-17 at 8 05 18 PM](https://user-images.githubusercontent.com/9577806/213081607-ff3928fa-395a-45d6-ab88-24f7c61d0c78.png)

**Comment by latenitefilms** [comment]
Do you have any issues with other FxPlug4 plugins? Do you use Color Finale, Chromatic, CoreMelt tools, FxFactory tools, etc? If you can get something else to break, then it might help problem solve.

Based on those screenshots, it definitely doesn't seem like the GPU is even getting close to capacity.

Just to triple check... is everything still playing back fine in the BRAW Toolbox Workflow Extension still? Do you get any stuttering or green frames in there, or is it only in Final Cut Pro?

**Comment by tangierc** [comment]
I hear you on getting something to break. I have a few FxFactory plugins, Coremelt Paint X and Slice X. 

Everything plays back fine in the BRAW Toolbox Workflow Extension.

**Comment by latenitefilms** [comment]
The only thing I can suggest is try contact Apple Support and see if their Final Cut Pro experts have any ideas. As far as I can tell, the plugin is doing it's job - it's just going funky in FCPX for whatever weird reason.

https://support.apple.com/en-au/final-cut-pro

**Comment by tangierc** [comment]
Chris is it possible to use the results of BRAW Toolbox on an FCP timeline in Resolve via XML? Just making sure I am not doing something wrong. 
I sent an XML of the timeline using clips from BRAW Toolbox and in Resolve I got the edits, but the video clips are non-vide clips that say “round trip dummy”,

I am trying to figure out how I would use BRAW Toolbox created clips in my edit and still pass this along to Resolve and a colorist for color grading.

**Comment by latenitefilms** [comment]
Yes, you can send a Project/Timeline from Final Cut Pro to DaVinci Resolve. You need to use this Toolbox:

https://github.com/latenitefilms/BRAWToolbox#convert-project-to-resolve-friendly-fcpxml-toolbox

**Comment by tangierc** [comment]
Thanks Chris. I misunderstood the initial use of that menu. All works well with it.

**Comment by latenitefilms** [comment]
I just heard back from someone on a **2013 Mac Pro with Dual AMD FirePro D700** and it's working fine on their system. No green frames. Playback performance isn't as good as on Apple Silicon or newer Intel's, however, if you render the footage in the timeline, it all works fine - so the effect is working. It seems maybe the CPU is just a bit too slow on these older Mac Pros.

One thing I never asked, if you render footage on your Mac Pro, does it render in the green frames and stuttering?

Given your screenshots show that you're not pushing the D500 much at all - I don't think increasing from D500 to D700 would make any difference, so I can only assume that it's actually your specific machine that has some kind of issue.

Have you tried another User account or booting into a fresh macOS install on an external drive or seperate partition?

**Comment by tangierc** [comment]
Thanks for the follow up. I guess it’s either just my machine or the clip itself.

I’ve swapped out the ports being used for the displays and drives.
The footage doesn’t have the green frames when rendered, but the stutter/jitter is more pronounced.
Tested on a new account. Same results.
Downloaded BRAW clips from BM site (first two clips on this page https://www.blackmagicdesign.com/products/blackmagicpocketcinemacamera/gallery <https://www.blackmagicdesign.com/products/blackmagicpocketcinemacamera/gallery>). They don’t have any of these issues.
Sending clips now - ETA 30 min upload. One screen recording, one for testing.

Tangier

**Comment by latenitefilms** [comment]
What was the difference between the BRAW files? Are the original clips higher quality?

It could just be a matter of your GPUs not being able to easily handle the resolution of 12K files or something?

Rather than using the Workflow Extension, you could try manually applying the BRAW Toolbox effect on a black generator in a HD timeline with the original clips and see if that works?

**Comment by latenitefilms** [comment]
Looking at the PDF you posted earlier, you're working with 6176x3472 BRAW files @ 23.976fps. The Workflow Extension will create a Sync Clip with the same resolution (regardless of Decode Quality), so again, maybe try making it UltraHD instead and see if that has any impact?

**Comment by tangierc** [comment]
I think at the end of the day it’s just the machine or machine config - eating two monitors. The same footage has no problems on my 2016 15” MBP with Touch Bar; single display and integrated graphics as mentioned before (and less video memory than any of my D500s in my Mac Pro. So it has to be the computer.

There’s something fundamentally wrong with that machine (the Mac Pro) managing the results of BRAW Toolbox.

My hardware test checked out fine.

The same issues showed up in a new user account.

Seems like one of those situations where the actual reason just won’t be discovered. It’s still a good machine and useful for a lot of things to me, but time to replace it.


Thanks Chris.

**Comment by latenitefilms** [comment]
I'm going to guess that the MacBook Pro will still work if you connect the same external monitors to it?

What results do you get if you run the Blackmagic BRAW Speed Test on both machines?

**Comment by tangierc** [comment]
Here's the results. The First is the 2013 3.5 GHz 6-core / Dual AMD D500s Mac Pro, the second is the 2016 Intel 15" MBP w/Touchbar 
![Screen Shot 2023-01-20 at 7 51 05 PM](https://user-images.githubusercontent.com/9577806/213842531-cc9485de-29e7-47a5-97f8-e71bd97d74b6.png)
<img width="798" alt="Screen Shot 2023-01-20 at 8 00 37 PM" src="https://user-images.githubusercontent.com/9577806/213842624-d04a682f-edb5-4777-869d-c15f87a3d615.png">

**Comment by latenitefilms** [comment]
So strange. Well, unfortunately I'm totally out of ideas.

I haven't heard anything back from Apple. I also haven't had any other feedback from other users reporting similar issues.

Given this, I'm going to close this issue for now, as I can only ASSUME it's something funky on that particular machine.

If I learn anything else, I'll definitely update this issue.

**Comment by latenitefilms** [comment]
@tangierc - If you have time, are you able to download the **v1.0.1** TestFlight release and see if that has any impact on your MacPro?

https://testflight.apple.com/join/GC92jL9o

**Comment by tangierc** [comment]
Chris, just to be sure - I have the purchased version installed already. I’ll be replacing that with the test version.

Tangier

**Comment by latenitefilms** [comment]
Yes, correct. Please close Final Cut Pro, send the `/Applications/BRAW Toolbox.app` from the Mac App Store to trash, then download the v1.0.1 beta from TestFlight and give that a go.

I have no idea if it'll have an impact or not - but hey, it's worth a shot!

**Comment by tangierc** [comment]
Hey Chris. I am doing everything I did before to duplicate the green and blue frames. They’re not there!

First I tested the new beta on old libraries that I used for testing BRAW Toolbox. These libraries had the issues show up.  This time they’re not there.
Next I created a new library and used BRAW Toolbox 1.01 beta to import the exact same clips. Still no green or blue frames.
I usually can invoke the frames by starting and stopping the playhead at random frames.
All of the above was playback in the browser. I tested in the timeline and the performance is the same - no strange flashing frames.

Whatever you did, looks to be successful and I am curious if you can share any insight.

Thanks,

Tangier

P.S. I did try moving my Mac Pro a little to the left as you suggested a little while ago, hoping that would fix the issue, but it didn’t…or did it? ;)

**Comment by latenitefilms** [comment]
Woohoo! Great news!

The main change I made, which I THINK is what is fixing your issue is that if a BRAW frame fails to render for whatever reason, we now retry five times before giving up. I'm not really sure WHY it fails in some cases - but at least now it tries five times first before outputting an error message.

There's still one remaining thing that I want to try solve in `v1.0.1` before I push out publicly - the BRAW Toolbox Renderer seems to be using a LOT of threads, which most likely means I'm not releasing something properly somewhere in the BRAW code. I'm currently working with Apple and Blackmagic to try and resolve this - but aside from that, it seems very stable and reliable on all the machines I tested it on.

**Comment by latenitefilms** [comment]
**v1.0.1 (34)** will hit TestFlight shortly. Are you able to check that it still works on your machine. Assuming all is good, this will be the version we release publicly. Thanks!

**Comment by tangierc** [comment]
Yes. I’ll check.Tangier On Feb 8, 2023, at 5:40 AM, Chris Hocking ***@***.***> wrote:﻿
v1.0.1 (34) will hit TestFlight shortly. Are you able to check that it still works on your machine. Assuming all is good, this will be the version we release publicly. Thanks!

**Comment by tangierc** [comment]
Hey Chris. It all still works well!

Tangier

**Comment by tangierc** [comment]
Chris, can you think of a clever way to relink to braw originals using BRAW Toolbox clips? I have an edit that already points to proxies (.mov files) made from braw clips. This was given to me. I am trying to figure out a way to point the original back to the braw counterpart, but BRAW Toolbox nor FCP can see the files that way.

Just curious if you can think of a workaround.

Thanks,

Tangier

**Comment by tangierc** [comment]
To clarify, the proxies made from the braw files are ProRes Proxies; seemingly made in Premiere Pro perhaps.

Tangier

**Comment by latenitefilms** [comment]
You could try this:

https://brawtoolbox.io/toolbox/#add-braw-toolbox-to-proxy-clips-within-an-event

If it doesn't work in this use case, send me a FCPXML via email and I'll have a think/play.

**Comment by tangierc** [comment]
Thanks Chris. I am trying to wrap my head around this after reading the instructions. My timeline already has ProRes Proxies made from the braw files by someone else, but the original .braw files were never used in an edit even before it was handed to me; only the .mov proxies. So there’s no current relationship between original .braw files and the proxies if I were to switch those playback options in FCP? 

Since I used an XML (via Send to X) to bring over the project from Premiere Pro

You’re saying that by taking events with the proxies, there will be a way for me to associate these proxies with the originals created by BRAW Toolbox so that toggling back and the playback in FCP will keep track of that in the same fashion we’re used to with other media?

I realize this isn’t ideal. The ideal situation is to just use the braw clips and change the decode settings so I don’t have to use the proxies. In FCP, replacing each proxy from the braw with a clip made by BRAW Toolbox would be a tedious and manual effort since I can’t tell FCP to point to the BRAW Toolbox created clips as the originals.

The only other option I can think of, (and it’s a long shot) is send the project out to Resolve using XML. Resolve has a replace feature, but I don’t know if it can batch replace clips. Even still, it would be pointing to the actual .braw files and not BRAW Toolbox clips.

I hope this makes sense.

Thanks again.

Tangier

**Comment by latenitefilms** [comment]
The **Add BRAW Toolbox to Proxy Clips within an EVENT** Toolbox basically does what it says - it adds the BRAW Toolbox effect to any of the `.mov` proxy files that exist in that Final Cut Pro event. The proxy file needs to be in the same folder as the BRAW file. So basically, "inside" each of your proxy clips, if you **Open Clip**, the BRAW Toolbox effect will be applied so you can modify the metadata there.

If it doesn't work, what you MIGHT have to do is **Open Clip**, apply any other effect (i.e. just apply a colour grade effect that doesn't do anything), and then try again - it really depends on what the FCPXML looks like coming back from SendToX.

Does that make sense?

**Comment by tangierc** [comment]
Got it. It does thank you. Would you mind explaining the extra characters in the name braw name of the Wav files created. I may need to explain this as I am using EDL-X to create an EDL. At first EDL didn’t take the name of the BRAW Toolbox-created clips. They came back null in the EDL. When I used EDL-X’s feature of adding an EDL-X share item in FCP and sent my timeline over that way, the EDL captured the name.  

Thanks Chris.

Tangier

**Comment by latenitefilms** [comment]
The extra characters at the end are just random characters. We add them because it's possible that a user might import several BRAW files that all have the same name, and the audio all lives in the one folder.

**Comment by tangierc** [comment]
That makes sense. I use EditReady to create a custom nomenclature so there can’t be duplicates for clips.

**Comment by tangierc** [comment]
Chris, have you tried BRAW Toolbox clips with EDL-X?  The team who I’ll be working with for color who will be using Resolve want the clips to nut be “null” for the clip name.  I’ll keep playing with the settings of EDL-X, but wanted to know if you’ve tried this out. Here’s a copy of a segment of my EDL for reference:

* FROM CLIP NAME: A003_A003_0223KZ_001.R3D
* ROLES: DIALOGUE  DIALOGUE.CAMERA
* AUDIO SOURCE CHANNELS: 1
* COM.APPLE.PROAPPS.STUDIO.REEL: A003_A003_0223KZ
* COM.APPLE.PROAPPS.STUDIO.REEL: A003_A003_0223KZ- 220429
* COM.APPLE.PROAPPS.STUDIO.SCENE: 175B
* COM.APPLE.PROAPPS.STUDIO.SHOT: 001
* COM.APPLE.PROAPPS.MIO.CAMERANAME: A
* COM.APPLE.PROAPPS.STUDIO.RAWTOLOGCONVERSION: 0
* COM.APPLE.PROAPPS.SPOTLIGHT.KMDITEMPROFILENAME: HD (1-1-1)
* COM.APPLE.PROAPPS.STUDIO.CAMERAISO: 0
* COM.APPLE.PROAPPS.STUDIO.CAMERACOLORTEMPERATURE: 0
* COM.APPLE.PROAPPS.SPOTLIGHT.KMDITEMCODECS: LINEAR PCM  LQ
* COM.APPLE.PROAPPS.MIO.SHOOTINGRATE: 23.976
* COM.APPLE.PROAPPS.MIO.MANUFACTURER: RED
* COM.APPLE.PROAPPS.MIO.MODELNAME: V-RAPTOR 8K VV
* COM.APPLE.PROAPPS.MIO.CAMERAID: A
* COM.APPLE.PROAPPS.MIO.CLIPFILENAME: A003_A003_0223KZ_001.R3D
* COM.APPLE.PROAPPS.MIO.INGESTDATE: 2022-12-04 20:31:12 -0800
008  106      V     C        00:00:42:19 00:01:12:18 00:01:01:00 00:01:30:23   
* FROM CLIP NAME: (NULL)
* ROLE: VIDEO
* COM.APPLE.PROAPPS.STUDIO.REEL: 5
* COM.APPLE.PROAPPS.STUDIO.SCENE: 1
* COM.APPLE.PROAPPS.STUDIO.SHOT: 99
* COM.APPLE.PROAPPS.STUDIO.ANGLE: B
* COM.APPLE.PROAPPS.MIO.CAMERANAME: BLACKMAGIC POCKET CINEMA CAMERA 6K PRO
* COM.APPLE.PROAPPS.MIO.INGESTDATE: 2022-02-17 13:52:00 -0800
* EFFECTS:
 BRAW TOOLBOX: FILE PATH  BOOKMARK DATA  DECODE QUALITY  ISO  EXPOSURE 
   COLOR TEMP  TINT  COLOR SCIENCE VERSION  COLOR SPACE/GAMUT  GAMMA 
   HIGHLIGHT RECOVERY  GAMUT COMPRESSION  LUT SOURCE  SATURATION 
   CONTRAST  MIDPOINT  HIGHLIGHT ROLLOFF  SHADOW ROLLOFF  BLACK LEVEL 
   WHITE LEVEL  USE VIDEO BLACK LEVEL
009  104      A1    C        00:00:42:19 00:01:12:18 00:01:01:00 00:01:30:23   
* FROM CLIP NAME: B005_02171452_C034-7644F8E3-BB46-4AC2-B53F-56BB3E032804.WAV
* ROLES: DIALOGUE  DIALOGUE.DIALOGUE-1
* AUDIO SOURCE CHANNELS: 1  2
* COM.APPLE.PROAPPS.STUDIO.REEL: 5
* COM.APPLE.PROAPPS.STUDIO.SCENE: 1
* COM.APPLE.PROAPPS.STUDIO.SHOT: 99
* COM.APPLE.PROAPPS.STUDIO.ANGLE: B
* COM.APPLE.PROAPPS.MIO.CAMERANAME: BLACKMAGIC POCKET CINEMA CAMERA 6K PRO
* COM.APPLE.PROAPPS.MIO.INGESTDATE: 2022-02-17 13:52:00 -0800
* COM.APPLE.PROAPPS.MIO.INGESTDATE: 2022-02-17 13:52:00 -0800
010  106      V     C        00:00:16:04 00:00:46:05 00:01:30:23 00:02:01:00   
* FROM CLIP NAME: (NULL)
* ROLE: VIDEO
* COM.APPLE.PROAPPS.STUDIO.REEL: 5
* COM.APPLE.PROAPPS.STUDIO.SCENE: 1
* COM.APPLE.PROAPPS.STUDIO.SHOT: 99
* COM.APPLE.PROAPPS.STUDIO.ANGLE: B
* COM.APPLE.PROAPPS.MIO.CAMERANAME: BLACKMAGIC POCKET CINEMA CAMERA 6K PRO
* COM.APPLE.PROAPPS.MIO.INGESTDATE: 2022-02-17 12:57:53 -0800
* EFFECTS:
 BRAW TOOLBOX: FILE PATH  BOOKMARK DATA  SHOW PARAMETERS  RESET
   METADATA  DECODE QUALITY  ISO  EXPOSURE  COLOR TEMP  TINT  COLOR
   SCIENCE VERSION  COLOR SPACE/GAMUT  GAMMA  HIGHLIGHT RECOVERY  GAMUT
   COMPRESSION  LUT SOURCE  SATURATION  CONTRAST  MIDPOINT  HIGHLIGHT
   ROLLOFF  SHADOW ROLLOFF  BLACK LEVEL  WHITE LEVEL  USE VIDEO BLACK
   LEVEL
011  005      A1    C        00:00:16:04 00:00:46:05 00:01:30:23 00:02:01:00   
* FROM CLIP NAME: B005_02171357_C028-922CD26E-1FD3-4E28-AC8D-C3FB137D6C35.WAV
* ROLES: DIALOGUE  DIALOGUE.DIALOGUE-1
* AUDIO SOURCE CHANNELS: 1  2
* COM.APPLE.PROAPPS.STUDIO.REEL: 5
* COM.APPLE.PROAPPS.STUDIO.SCENE: 1
* COM.APPLE.PROAPPS.STUDIO.SHOT: 99
* COM.APPLE.PROAPPS.STUDIO.ANGLE: B
* COM.APPLE.PROAPPS.MIO.CAMERANAME: BLACKMAGIC POCKET CINEMA CAMERA 6K PRO
* COM.APPLE.PROAPPS.MIO.INGESTDATE: 2022-02-17 12:57:53 -0800
* COM.APPLE.PROAPPS.MIO.INGESTDATE: 2022-02-17 12:57:53 -0800
012  015      V     C        12:48:50:06 12:49:20:06 00:02:01:00 00:02:31:00   


Tangier

**Comment by latenitefilms** [comment]
Try using "Top-Level Clip Names":

<img width="1257" alt="image" src="https://user-images.githubusercontent.com/22286696/218970926-bbcf4e1e-83e8-4837-b112-9c5474728363.png">

<img width="1257" alt="image" src="https://user-images.githubusercontent.com/22286696/218971018-3687f969-dab0-4f65-bc8a-2c8ffcccf005.png">

Although, I am curious why you're using a EDL for Resolve and not a FCPXML?

**Comment by tangierc** [comment]
Hey Chris. I need help trying to understand something. Is it possible to have copies of BRAW clips on two separate drives and relink as needed without having to got inside each clip to select BRAW file? I do this because at home I have my Red R3D original files that I can have FCP switch to original playback with the BRAW clips. My mobile drive can’t accommodate that much space so I use prores proxies of the RED files paired and want to pair that with copies of the BRAW clips. It’s a matter of storage. 

I did a test this morning where I created a library on Drive 1 where I keep libraries exclusively (no media) with three BRAW clips that are on Drive 2 (my home drive). 
I have a copy of those same BRAW clips on my mobile drive - Drive 3.
I opened the same library but want to redirect the library to look at Drive 3
Of course, they’re offline with the missing file, security-scoped bookmark issue.
I open one clip to grant sandbox access to the folder with the clips, but none of the clips update and link.

I realize that one option is just use the mobile drive as the originals for everything, but I need to be able to switch to Drive 2 if I am handing the project over.

Could you assist please?

Sincerely,

Tangier
